name: Deploy to Railway

on:
    push:
        branches:
            - development
            - qa
            - uat
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Railway CLI
              run: npm install -g @railway/cli

            - name: Set Environment Variables
              run: |
                  if [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
                    echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN_DEV }}" >> $GITHUB_ENV
                  elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
                    echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN_DEV }}" >> $GITHUB_ENV
                  elif [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
                    echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN_DEV }}" >> $GITHUB_ENV
                  elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                    echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN_DEV }}" >> $GITHUB_ENV
                  fi

            - name: Deploy to Railway
              run: railway up  --service turborepo-ci-railway
              env:
                  RAILWAY_TOKEN: ${{ env.RAILWAY_TOKEN }}
